version: '3.7'

services:

  caddy_server:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    ports:
      - 80:80
      - 443:443
    networks:
      - caddy
    environment:
      - CADDY_DOCKER_MODE=server
    volumes:
      # this volume is needed to keep the certificates
      # otherwise, new ones will be re-issued upon restart
      - caddy_data:/data
    deploy:
      replicas: 3
      labels:
        caddy_controlled_server:

  caddy_controller:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    networks:
      - caddy
    environment:
      - CADDY_DOCKER_MODE=controller
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # Proxy to service
  whoami0:
    image: containous/whoami
    networks:
      - caddy
    deploy:
      labels:
        caddy: whoami0.example.com
        caddy.reverse_proxy: "{{upstreams 80}}"
        # remove the following line when you have verified your setup
        # Otherwise you risk being rate limited by let's encrypt
        caddy.tls.ca: https://acme-staging-v02.api.letsencrypt.org/directory

  # Proxy to service
  whoami1:
    image: containous/whoami
    networks:
      - caddy
    deploy:
      labels:
        caddy: whoami1.example.com
        caddy.reverse_proxy: "{{upstreams 80}}"
        caddy.tls: "internal"

  # Proxy to container
  whoami2:
    image: containous/whoami
    networks:
      - caddy
    labels:
      caddy: whoami2.example.com
      caddy.reverse_proxy: "{{upstreams 80}}"
      caddy.tls: "internal"

  # Proxy to container
  whoami3:
    image: containous/whoami
    networks:
      - caddy
    labels:
      caddy: whoami3.example.com
      caddy.reverse_proxy: "{{upstreams 80}}"
      caddy.tls: "internal"

  # Proxy with matches and route
  echo_0:
    image: containous/whoami
    networks:
      - caddy
    deploy:
      labels:
        caddy: echo0.example.com
        caddy.@match.path: "/sourcepath /sourcepath/*"
        caddy.route: "@match"
        caddy.route.0_uri: "strip_prefix /sourcepath"
        caddy.route.1_rewrite: "* /targetpath{path}"
        caddy.route.2_reverse_proxy: "{{upstreams 80}}"
        caddy.tls: "internal"

networks:
  caddy:
    name: caddy
    driver: overlay

volumes:
  caddy_data: {}
